#!/usr/bin/env python3

import pandas as pd
34
dtype_dict = {

    'committee_id': str,
    'committee_name': str,
    'report_year': str,
    'report_type': str,
    'image_number': str,
    'line_number': str,
    'transaction_id': str,
    'file_number': str,
    'committee_name': str,
    'entity_type': str,
    'entity_type_desc': str,
    'unused_contbr_id': str,
    'contributor_prefix': str,
    'contributor_name': str,
    'recipient_committee_type': str,
    'contributor_first_name': str,
    'contributor_middle_name': str,
    'contributor_last_name': str,
    'contributor_suffix': str,
    'contributor_street_1': str,
    'contributor_street_2': str,
    'contributor_city': str,
    'contributor_state': str,
    'contributor_zip': str,
    'contributor_employer': str,
    'contributor_occupation': str,
    'contributor_id': str,
    'receipt_type': str,
    'receipt_type_desc': str,
    'receipt_type_full': str,
    'memo_code': str,
    'memo_code_full': str,
    'contribution_receipt_date': str,
    'contribution_receipt_amount': float,
    'contributor_aggregate_ytd': str,
    'candidate_id': str,
    'candidate_name': str,
    'candidate_first_name': str,
    'candidate_last_name': str,
    'candidate_middle_name': str,
    'candidate_prefix': str,
    'candidate_suffix': str,
    'candidate_office': str,
    'candidate_office_full': str,
    'candidate_office_state': str,
    'candidate_office_state_full': str,
    'candidate_office_district': str,
    'conduit_committee_id': str,
    'conduit_committee_name': str,
    'conduit_committee_street1': str,
    'conduit_committee_street2': str,
    'conduit_committee_city': str,
    'conduit_committee_state': str,
    'conduit_committee_zip': str,
    'donor_committee_name': str,
    'national_committee_nonfederal_account': str,
    'election_type': str,
    'election_type_full': str,
    'fec_election_type_desc': str,
    'fec_election_year': str,
    'amendment_indicator': str,
    'amendment_indicator_desc': str,
    'schedule_type_full': str, 'load_date': str,
    'original_sub_id': str,
    'back_reference_transaction_id': str,
    'back_reference_schedule_name': str,
    'filing_form': str,
    'link_id': str,
    'is_individual': str,
    'memo_text': str,
    'two_year_transaction_period': str,
    'schedule_type': str,
    'increased_limit': str,
    'sub_id': str,
    'pdf_url': str,
    'line_number_label': str

}
df = pd.read_csv('data/kamala/schedule_a-2019-01-29T21_37_01.csv', dtype=dtype_dict)
